/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vn.test.interview;

import java.sql.Array;
import java.util.ArrayList;
import java.util.Currency;

public class App {

    public static void main(String[] args) {

        var givenArr = new ArrayList<Long>();

        var currentFibNum = 1L;
        var nextFibNum = 1L;
        int firstCurrentFibIndex = findIndex(givenArr, 1, 1);
        if (firstCurrentFibIndex == -1) {
            System.out.println(0);
            return;
        }

        int nextFibIndex = findIndex(givenArr, 1, 2);
        if (nextFibIndex == -1) {
            System.out.println(1);
            return;
        }

        var longestFibArrLen = 2;
        for (int i = nextFibIndex + 1; i < givenArr.size(); i++) {
            if (givenArr.get(i) == currentFibNum + nextFibNum) {
                currentFibNum = nextFibNum;
                nextFibNum = givenArr.get(i);
                longestFibArrLen++;
            }
        }

        System.out.println(longestFibArrLen);
    }

    public static int findIndex(ArrayList<Long> givenArr, int val, int givenCount) {
        int tmpCount = 1;
        for (int i = 0; i < givenArr.size(); i++) {
            if (givenArr.get(i) == val) {
                if (tmpCount == givenCount) {
                    return i;
                } else {
                    tmpCount++;
                }
            }
        }
        return -1;
    }
}
